# Generated by Django 4.2.4 on 2023-08-13 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category_portfolio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='project_img',
            field=models.CharField(max_length=400),
        ),
    ]
